dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"

dotenv: .env

networks:
  default: development
  rinkeby: ""

wallets:
  from_key: ${PRIVATE_KEY}
